name: pangeo-forge-exploration
platforms:
  - linux-64
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.11.0
  - pangeo-forge-recipes ~=0.10.7
  - apache-beam ~=2.54.0

  - pip
  - pip:
    - pangeo-forge-runner ~=0.10.2
    - venvception
